### ISSUE TITLE
De latitude / longtitude onbreekt in deze query

### ISSUE THREAD

**Issue by JeroenHeemskerk** [uknowwho/educom-data-science-1714723739#23]
In de query hieronder
https://github.com/uknowwho/educom-data-science-1714723739/blob/748530876e98bebbcc615564cd4694ab04f66e7a/relational-data-storage/opdracht-4/DS-opdracht-4.1.5.sql#L1-L4
Ontbreken de lat en long (uit postcode tabel) in het resultaat
van leverancier zou alleen naam, straat, huisnummer en postcode moeten worden getoond

**Comment by uknowwho** [comment]
Opvallend, bij mij staan de lat en lng er wel bij omdat ik * aanroep en de pc_lat_long tabel join. Ik heb nu de specifieke juiste kolommen geselecteerd.
